export const Images = {
  about: require('./about.png'),
  account: require('./account.png'),
  accountActive: require('./account_active.png'),
  arrowRight: require('./arrow-right.png'),
  bag: require('./bag.png'),
  bg: require('./bg.png'),
  calendar: require('./calendar.png'),
  call: require('./call.png'),
  chatBubble: require('./chat_bubble.png'),
  coupon: require('./coupon.png'),
  couponCard: require('./coupon_card.png'),
  eye: require('./eye.png'),
  gender: require('./gender.png'),
  heart: require('./heart.png'),
  help: require('./help.png'),
  home: require('./home.png'),
  homeActive: require('./home_active.png'),
  homescreenBg: require('./homescreenBg.png'),
  location: require('./location.png'),
  lock: require('./lock.png'),
  logo: require('./logo.png'),
  logout: require('./logout.png'),
  loyality: require('./loyality.png'), // Keeping original spelling 'loyality' to match file
  loyaltyCard: require('./loyalty_card.png'),
  mail: require('./mail.png'),
  name: require('./name.png'),
  order: require('./order.png'),
  orderHistory: require('./orderHistory.png'),
  orderActive: require('./order_active.png'),
  orderr: require('./orderr.png'),
  password: require('./password.png'),
  search: require('./search.png'),
  settings: require('./settings.png'),
};
